const sql = require('mssql');
const config = require('./dataConfig');

async function insertDTs() {
    try {
        // Connect to the database
        await sql.connect(config);

        // List of DT names
        const dtNames = [
    "By NEPA", "Gayawa Relief", "Abba Boss", "MD Customer", "2nd Transformer Badawa Quarters",
    "Badawa Police Station", "First Transformer", "Oliver", "Alhaji Sule Old", "Engineer Shaaibu",
    "Mai Unguwa", "Mainasara Public", "Baba Brothers", "Gidan Kara", "Jaba Masallaci", "Dan Fulani",
    "Residential Old", "Dan Sokoto", "Wazobia", "TYC", "FRANCE RD/POLICE STATION", "Freetown Goldcoast",
    "Odutola", "IDH", "Joint 99", "Durunguma", "Barka Da Zuwa", "Old Pplice Barrack",
    "Barka Da Zuwa Relief", "Residential Relief", "Caesar Avenue", "Ibadan Church Road", "Remco",
    "New Road", "Coca Cola", "Ceasar Avenue", "Festing France Road", "Ado Auditor", "Dantata Shops",
    "DIO", "Yan Katako", "Umar Shehu Minjibir", "Ed Finance Sankore", "Habibu Sale", "Gm Ringim",
    "Hussaini Sagagi", "Dan Kuli Relief", "Aminuddeen 3", "Engr Wali", "Giginyu Junction", "Alhaji. Ali",
    "Police Barracks 1", "Jaba 2", "Baban Gwari", "Ashton Road", "AGIP Round About", "Panasonic",
    "REB Bola", "Smash Leg", "Tafawa Balewa", "President Avenue", "Ubale Garko Old", "SP", "Yau Usman",
    "Tudun Wada Old", "Yakudima Qtrs", "Fountain Estate", "PZ", "Rwaff Road Jafar", "Yoruba Road Igbo Road",
    "Aitken Court Road", "Zonah Pharmacy", "J Herman", "Fan Milk Old", "Yan Kaji", "Unguwar Yarbawa 1",
    "Unguwar Yarbawa 2", "Miltara Yamma Kadawa 2", "Kadawa Relief", "Railway Quarters", "Ajasa", "No1 Sultan Tukur Road",
    "Alu Avenue", "Balarabe Bello", "Hongfu Restaurant", "Nassarawa Business Unit", "No12 Natsugunne", "Ado Bayero",
    "Yan Katifa Relief", "Mallam Kato", "Yan Tumatur", "UDB Road One", "Aminu Road", "Redeemed Church", "Bello Road",
    "Minstry Of Agriculture", "Sabuwar Doka", "Nura Mai Mai", "Alu Avenue Ahmadu Bello", "Batawa Close", "Aba Igbo Road",
    "Jajira 3", "Tsamiyar Zubau", "Sale Old", "Sale Relief", "Sani Kamba", "Warure", "No1 Korou Road", "Gidan Shehu",
    "Borno Avenue", "Babura", "Abdulmumini Estate", "Charge Office", "SASIF", "Gama Fulani", "Hajiya Faiza", "Gawuna Old",
    "Maharaja", "Sale", "Jangaru Kunture Ungogo", "Ungogo 2", "Walawa Fanisau", "Ungogo 1", "Minkyau", "Miltara Gabas Kadawa 1",
    "Jajira 1", "Mai Kifi", "Mai Takalmi Old", "Ali Babar", "Cemetry", "Gidan Kwari 1", "Hajiya Dije", "UDB Road Two",
    "Rijiya Uku", "Doka Dawa", "Lajawa", "Maigemu", "Ubale Garko Relief", "Union Homes", "Second Transformer", "Gidan Goldie",
    "No2 Korau Road", "Shawwal", "Jagule", "Niger Court Road", "Aba Road Relief", "Ibadan New Road", "Director SSS", 
    "Dr Bala Muhammad", "Mangal Residence", "Shehu Media", "Unity Estate", "Rainbow", "Tsauni Badawa Bustop", "Farar Gona",
    "Keera Village", "Abbas Road", "Darerawa", "Bagery Close Road", "Doka Cikin Gari", "Yusuf Road", "AVM Mukhtar Mohd Residence",
    "Sharifai", "Alhaji Sule Relief", "Hali Brothers", "Zango Bachirawa", "215 No5 Ibrahim Dabo Road", "Kuwait Old", "NITEL Quarters",
    "Bukavo Barracks", "Chikenza", "Yan Dutse Road", "Yar kasuwa", "Fatima Habib", "Umar Galadima", "Hector", "Gongoni",
    "Yan Tsafta", "Tajo", "Ibadan France Road", "Ishewu", "Joint 99 Relief", "Aitken Lafiya Surgery", "Ogidi Harmony", 
    "Ijebu Road by Paro Hotel", "PRP 1 Yan Rake", "Custom Barrack", "ATA", "Assemblies Of God", "De Friendship", 
    "Festing New Road", "Kuwait Relief", "Giginyu", "Enugu Igbo Road", "Yar Adua Quarters", "Goldcoast Aitken", "New Kowa", 
    "Sarkin Yaki Burma Road", "Goldcoast Burma Road", "Brisco", "Layin Mai Unguwa", "Church Road Igbo Road", "Peter Obiebi Relief",
    "Arewa 24", "IO Lawan", "Aviation Quarters", "Durbush", "160 FIRS Commissioner Road", "Gayawa Old", "AIG", "Kandahar", 
    "Tsamiya", "Romeo", "Gadar Katako", "Rimi Maishadda Public", "Dawaki", "Arakan Road", "Guda Abdullahi HVDS", 
    "Ahmadu Bello Danbazau", "Mai Takalmi Relief", "Paro Hotel", "Baba Tela", "Dan Damuna", "Wellcare 1", "KETAWA", 
    "Getsi", "Tudun Murtala Old", "Zangon Marikita", "Gidan Bredi", "Unguwan Malamai", "Umar Faruq Ibrahim Kwairanga", 
    "Zagon Marikita", "Badaru", "Alhaji Muazu", "Yar Kasuwa Tudun Murtala", "Ramin Gemu", "Agantasa", "Yahaya Bagobiri", 
    "GNT", "Maganda", "Sergent Digasa", "Yaradua", "Old Cemetry", "Dan Tamashe", "Galula Dispensary", "Yan Tumaki Relief", 
    "Mai Riga", "Mai Riga REB", "Ranji", "Dan Kargo", "Gama Tudu", "Zangon Marikita Upr 1", "Mai Nama", "Dankunkuru", 
    "Dabinai Uku", "Gidan Mai Garin Tudun Wada", "Green White Green Relief", "R. M. U.", "Mai Anguwa", "GTC Quarters", 
    "Kasuwar Mata", "Audu Gama", "Remco", "Kuka Daya", "Dosara", "Rimaye", "Yan Awaki", "Yan Kwalla 2", "PRP 2", 
    "Nura Hamisu", "Halilu Mai Shanu", "Hajiya Kulu", "Gama Sabuwa", "Asasco Bichi", "Dan Juma", "Hassan Ibrahim", 
    "Kwanar Jaba Old", "Kankare Kutare", "Rimin Dillalai 1", "Sabon Birni Kofar Fada Kankia", "Saresare", "Bogwai Sabuwa", 
    "Tsohuwar Yan Kamaye", "Lamba Kunchi", "Badume Village", "Goruba", "Kwanar Jaba 2", "Chiranchi Bichi", "Bichi Secretariat", 
    "Malikawa Garu", "Dan Zabuwa", "SAYE RELIEF", "Ibrahim Muazzam Bichi", "Roni Kanti", "Tsanyawa 2 Relief Police Station", 
    "Rimaye Bakin Makaranta", "Ahamadiyya", "Sabena", "Abdullahi Soja", "Rimin Dillalai 2", "Tsanyawa Unguwar Gabas", 
    "Santar Sabo Village", "Tudun Wulli Village Bichi", "Mazara Tsaraka", "Dansiri Village", "Old NEPA Bichi", "Kyauta Village", 
    "FCE Road Bichi", "Santar Rago", "FCE Road Bichi Relief",  "Yantama",    "Faskar Maaji",
    "Tashar Idi",
    "Dumaji",
    "Garun Mallam Old",
    "Bebeji Hospital Relief",    "Anadariya Gari 1",
    "Dakatsalle Relief",
    "Kofa 3",
    "Dakatsalle 1",
    "Gwarmai 1",
    "Yar Fulani",
    "Faskar Wambai",
    "Mahuta",
    "Falgore Gidan Sarki",    "Anadariya Gari 2",
    "Riruwai S Layi",
    "Kanwa Gidan Sarki",
    "Burji Hayan Allo",
    "Bahawa",
    "Mashaya",
    "Tiga Mosque",
    "Tudun Wada Kasco",
    "Kyangyaran",
    "Yar Yasa",
    "Tashar Inji",
    "Yalwan Rugu Rugu",
    "Daburau",
    "Sabuwar Unguwa Bebeji",
    "Fegin Shaa",
    "Kabuga Primary Old",
    "Unguwar Nadabo Relief",
    "Hayin Tarau",
    "Gwarmai 2",
    "Durmawa Bebeji",
    "Tagwaye",
    "Falgore Police Station",
    "Tiga Yankifi",
    "Bebeji 2",
    "Yan Alewa",
    "Kadawa Hadejia Jamaare",
    "Tiga Yanshinkafa Dirimawa",
    "Bebeji Layout",
    "Tsohuwar Kasuwa",
    "Sumana",
    "Dangora A",
    "Dangora B",
    "Jataka",
    "Yar Ganji",
    "Karfi Yan Shinkafa",
    "Dididi",
    "Hadejia Jamaare Kura",
    "Yadakwari Cikin Gari",
    "Gana",
    "Danbubu",
    "Masallacin Idi",
    "Rijiyar Zaki Primary",
    "Rahama Round 2",
    "Doka",
    "Masallacin Jumaa",
    "Malamawa 1",
    "Maikalwa primary Relief",
    "Mera",
    "Juahco Relief",
    "Dan Jirma",
    "Gidan Kaji",
    "Tsamiyar Amawa",
    "Ranka",
    "Yan Doya",
    "Hamudi",
    "Yalwa",
    "Dogon Kawo",
    "Sabon Garin Doguwa",
    "Motar Soja Old",
    "Northwest",
    "Akram Tudun Yola",
    "Gajale",
    "Dandishe Old",
    "Yan Dilalai Relief",
    "Bada",
    "Gobirawa Village",
    "Dagachin Gobirawa",
    "Unguwar Nadabo Old",
    "Yanshinkafa",
    "Kofar Yamma Dawakin Tofa",
    "Dabai Massallaci",
    "Shago Tara Kurna",
    "Kwiwa Yamma",
    "Manladan",
    "Samawa Waje",
    "Chedi",
    "Kotu",
    "Gwani Dan Zarga",
    "Danzago",
    "Hawan Dawaki",
    "Kazamin Bene",
    "Unguwar Haladu",
    "Sharu Uba",
    "Ruwan Kanya",
    "Kwiwa Gabas",
    "Tudun Doka",
    "Agalawa Yako",
    "Muawiyya",
    "Yan Nama",
    "Mai Selula",
    "Malamai",
    "Dan Maradi Relief",
    "Dabai Yan Tanki",
    "Dan Mora",
    "Kofar Ruwa B",
    "Yan Mata Yamma",
    "Dabai Sabon Rami",
    "Chiromawa",
    "Dandishe Gabas",
    "Dausayi 2",
    "Bajallabe",
    "Sabon Rami",
    "Farin Massalachi",
    "Albarka",
    "Dawakin Tofa Kofar Fada",
    "Unguwar Kudu",
    "Jajira",
    "Ammasco",
    "Ado Bayero Relief",
    "Dungurawa",
    "Kwanar Dillalai Unguwar Wambai",
    "Dawanau Market",
    "Kofar Gabas Dawakin Tofa",
    "Engineer Burkullu",
    "Layin Barrister",
    "Unguwar Wambai",
    "Tudun Yola Gate 4",
    "Azman Dan Aljannah",
    "Rimin Auzinawa",
    "Mairariya Relief",
    "Mairariya Old",
    "Sarauniya",
    "Bagadawa",
    "Zangon Yan Kwando",
    "Mai Unguwa Old",
    "Daboro",
    "Darul Hadith Tudun Yola",
    "Iyan Tama",
    "Rimin Gata 2",
    "Samegu Masallachi",
    "Kofar Arewa Dawakin Tofa",
    "Janbulo Second Gate",
    "Kwarin Adiya",
    "Waika Waje",
    "Fagen Kawo",
    "Yan Shia",
    "RN Sule Relief 1",
    "Danbare East Old",
    "Bugaje",
    "Kadawa",
    "Conoil Filling Station",
    "IO Lawal",
    "R/ZAKI PRIMARY",
    "Yamadawa Chairman Old",
    "Janguza Village 2",
    "Ibrahim Khalil Relief",
    "Jega Tudun Yola C",
    "Kabuga Relief",
    "Yan Kilishi",
    "Janguza Tudun Malamai",
    "Tudun Yola Gate 1",
    "Tumfafi 2",
    "Tasiu Relief",
    "Kuyan Ta Inna North",
    "Katsinawa",
    "Ubale Custom",
    "Sadiq Old",
    "Lawan Coach",
    "Janguza Village 1",
    "Tafida Relief",
    "Bakin Gada",
    "Masallaci Fagge",
    "Sadiq Relief",
    "Tasiu Old",
    "Zirin Gaza Tudun Yola",
    "Kwa Old",
    "Danbare Primary School",
    "AGM",
    "Sir Sanusi",
    "Dan Bare East Relief 2",
    "Haladu Relief",
    "Gidan Magani Old",
    "Unity",
    "Ibrahim Khalil",
    "Yan Tabarma",
    "Andal Science Academy",
    "Dr Ahmad Tudun Yola",
    "Haladu Old",
    "Samegu Unguwan Liman",
    "Dambazau",
    "Yan Goro",
    "Gangaren Dutse",
    "Dausayi 1",
    "Alfa",
    "Yusuf Ibrahim",
    "Dan Bare East Relief",
    "Sule Chamba Relief",
    "Yamadawa Chairman Relief 2",
    "Tafida Old",
    "Kuyan Ta Inna Relief",
    "Dausayi 3",
    "Garba Izala Relief",
    "Danbare Quarters",
    "Rimin Gata",
    "Rimin Auzinawa Relief",
    "Kwaciri Maidorawa",
    "Samegu Gidan Inji",
    "Dau Aliyu 1",
    "Fegin Liman",
    "Dandali Relief",
    "Ring Road",
    "Hauwa Bala",
    "Mai Unguwa Relief",
    "Nafiu Mai Arna",
    "Ghali Sadiq 1",
    "Zangon Kaya",
    "Alhaji Kabiru KEDCO Head Driver",
    "Gangarruwa",
    "Shekara",
    "Rafin Dan Nana",
    "Society",
    "Tudun Yola Gate 5",
    "Lawan Coach Relief",
    "Dangada",
    "Halilu Old",
    "Kwarawa Relief 2",
    "Masallacin Jalli",
    "Sani Dawaki",
    "Alasawa",
    "Ghali Sadiq 2",
    "Layin Damisa",
    "KEDCO Office Kurna",
    "RN Sule Relief 2",
    "Yar Gargagiya",
    "Jega Relief",
    "Madachi",
    "Dandishe Yamma Asibiti",
    "Gidan Wanka",
    "Gadar Salga",
    "Sabon Birni",
    "Sule Chamber",
    "Yakasai Bola",
    "Emergency MMSH",
    "Dukawuya Old",
    "Nasiru Ahli",
    "Tudun Yola C Relief",
    "Mallam Hassan Gada Relief",
    "Uzoma",
    "Shekara GGS",
    "Filin Wali",
    "Gidan Ruwa",
    "Kofar Mata Relief",
    "Maroosh",
    "Yan Dabino",
    "Gidan Magani Relief",
    "Dankoli",
    "Major Hadi Relief 1",
    "Dan Masani Kwalli",
    "Kofar Mata",
    "Kusurwa Relief",
    "Kofar Mata Stadium",
    "Diso Relief",
    "Dr Yakasai",
    "Police Barracks",
    "Wali Old",
    "Kurna Makaranta",
    "Gudindi 2",
    "Zaitawa",
    "Dakalin Gwamna",
    "Yan Wanki",
    "Wajila",
    "Madatai",
 "Major Hadi",
    "Uba Ringim",
    "Agadasawa",
    "Kwalwa 1",
    "Makwarari 1",
    "Durumin Zungura",
    "Gada Rijiyar Lemo Azman",
    "Aliko Oil CSR",
    "Yan Santsi",
    "Engr Surajo REB",
    "Alkantara",
    "Darbejiya",
    "Dan Goruba Relief",
    "Tumfafi 1 Gabas Old",
    "Yola Old",
    "Nassarawa Garden",
    "Madaki",
    "Uba Waru Relief",
    "Yan Itace",
    "Kofar Nassarawa",
    "Uba Waru",
    "Daneji",
    "Kofar Mazugal",
    "Yar Kuranga",
    "Wambai Bola",
    "Honourable Ata",
    "Alkali Hamza",
    "Dan Masani Unity Road",
    "Ado Bayero Islamiyya",
    "Masallaci Kofar Mata",
    "Zango Yan Madubi",
    "Goron Dutse Prison",
    "Samaila Relief",
    "Farin Gida",
    "Gwale LEA Relief",
    "Gadar Yar Ai 1",
    "Kusurwa",
    "Kurawa Old",
    "Zango",
    "Aisami Relief",
    "Soron Dinki 2",
    "NA-SALE UMAR ALH",
    "Yan Kwanuka",
    "Kabuga Bataiyya Relief",
    "Kwanar Goda",
    "SAS",
    "Gudindi 1",
    "Bala Rabiu",
    "Bakin Kasuwa Kabo",
    "Hauren Balagu",
    "Karofin Sudawa 2",
    "Garangamawa",
    "Soron Dinki",
    "Samaila Old",
    "Marina Kofar Mata",
    "Rijiyar Lada",
    "Dan Koli",
    "Kamfa",
    "Kwalwa 2",
    "Kabuga Bataiyya Gate",
    "Kabara Relief",
    "Chiranchi",
    "Mandawari 2",
    "Ayagi",
    "Mangoran Miara",
    "Warure 2",
    "Malam Jafar",
    "Gwale LEA Old",
    "Jakara Maternity Relief",
    "Marmara Hospital 1",
    "Sallau Musa",
    "Madatai Primary Relief",
    "Dan Dawaki",
    "Rabiu Speaking Relief",
    "Mubi Relief",
    "Gwale Vetinary Relief",
    "Kwanar Gabari",
    "Bachirawa Unguwar Yarbawa Old",
    "Filin DO Relief",
    "Warure 1",
    "Dorayi 1",
    "Dorayi 2",
    "Filin Mushe Old",
    "Education Quarters",
    "Sadiq",
    "Jakara Maternity",
    "Kwalli Primary School",
    "Dangwalalo Relief",
    "Dala Old Secretariat",
    "Nababa Relief",
    "Rabiu Speaking",
    "Kaura Merchant",
    "Mabo Yar Maishinkafi",
    "Kadara",
    "Karofin Sudawa 1",
    "Fillin Mushe Relief 1",
    "Baba Dan Baffa",
    "Gamco",
    "WTC Goron Dutse Quarters",
    "Kuka Uku",
    "Mangoran Miara Relief",
    "Wali Relief",
    "Rijiyar Dan Kada",
    "Kabara Old",
    "Fillin Mushe Relief 2",
    "Filin DO Old",
    "Gareka Layin Service",
    "Bayan Sani Abacha Youth Centre",
    "Aisami Asibiti",
    "Lado",
    "Yan Kifi",
    "Al Amir",
    "Yan Dabino Gadon Kaya",
    "Mobil",
    "Dandago Yan Itace",
    "Maitangaran 1",
    "Dan Bala",
    "KURFI 2",
    "Elkanemi",
    "Jakara Bola",
    "Diso Old",
    "Hauran Legal",
    "Plaza",
    "Abacha",
    "Ali Baba",
    "Central Prison",
    "Yan Jakai",
    "Dr Ayagi",
    "Marmara Hospital 2",
    "Banufiya",
    "Yan Katifa Old",
    "Izazudden",
    "Sarari Primary School",
    "Dandali Old",
    "Makafin Dala",
    "Wakilin Arewa",
    "Bakin Zuwo",
    "Yan Kekuna",
    "Alkali",
    "Koki Old",
    "Yan Gado",
    "B Oloja Relief",
    "Wakilin Gabas Relief",
    "Jar Kasa",
    "Dawanau Dandishe Yamma",
    "Yan Dusa",
    "Kabarin Wali Kofar Waika",
    "Sunusi Dantata Relief",
    "Mandawari",
    "Masaka Primary Old",
    "Yusi Ilu",
    "Jalli",
    "Binta Sayyadi",
    "Gidan Boss",
    "Malfa Old",
    "Gwale Vetinary",
    "Mararraba",
    "Mandawari 3",
    "Jaen Yamma",
    "Mai Aduwa Old",
    "Musa UAC",
    "Gwammaja Housing Estate 1",
    "Sunusi Dantata Old",
    "Man Ladan",
    "Yan Dilalai",
    "Tattarawa",
    "Dakatsalle",
    "Kano Guest Inn Old",
    "Masaka Primary Relief",
    "Tijjani Mai Lafiya",
    "Wapa Relief",
    "Malfa Relief",
    "Wapa Old",
    "Yan Awaki Relief",
    "Madigawa",
    "Nasidi Mai Gwanjo",
    "UBA Public",
    "Oria",
    "Haruna Kassim",
    "Tagwayen Gida Old",
    "Nassarawan Bagadawa",
    "Kwanar Dawaki",
    "Isah Kafinta Old",
    "Kwanar Taya",
    "Kofar Waika Badala",
    "Dandalama",
    "Makabarta Old",
    "GGC Dala Orthopaedic",
    "Yan Welder Kofar Dawanau",
    "Isah Kafinta Relief",
    "Yalwan Nasidi Abubakar",
    "Ladio",
    "Gwammaja Bola",
    "Gwammaja Housing Estate 2",
    "Babawa Ranawa",
    "Gerawa Farawa",
    "Sarki Illiyasu 1",
    "HVDS DT",
    "Yan Awaki Old",
    "Abattoir",
    "Gangaren Dutse Kwa",
    "Yan Sona",
    "Hayin Hago",
    "Yakasan Dandalama",
    "Yan Kabewa",
    "Galadima",
    "Masallaci Old Masaka",
    "Gwammaja 2",
    "Dala Secretariat",
    "Kukah Idau",
    "Wakilin Gabas Old",
    "Hajiya Bara",
    "Alhaji Bashir",
    "Yalwan Yan Itace",
    "Limawa Old",
    "YANDODO RELIEF",
    "Makabarta Relief New",
    "Dan Inu",
    "Jogana Mai Unguwa",
    "Sayoka Mai Block",
    "Tagwayen Gida Relief",
    "Dangwalalo Old",
    "Kabarin Wali",
    "Masallaci Relief Yan Charko",
    "Masaudu",
    "Mai Gari",
    "Raudakayi 1",
    "Wudil Secretariat",
    "Magami 1",
    "Panda",
    "Kwanar Yashi",
    "Gunduwawa Mosque",
    "Wudil Sakau",
    "Sauna Crusher",
    "Gwaron Dutse Primary",
    "WRECA Old",
    "Yan Itace Gwammaja",
    "Chairman Relief",
    "Zagi Relief",
    "Tudun Gunsau",
    "Gwagwarandan",
    "Sauna Masallaci",
    "Kuka Old",
    "Layin Kuka",
    "Rakkad",
    "Dan Goruba Old",
    "Dangwalalo Relief 2",
    "Dan Zaki 1",
    "Sabo Bakin Zuwo",
    "GGC Dala",
    "Yan Welder Kofar Ruwa",
    "Indabo",
    "Tin shama Old",
    "Tashar Kuturu",
    "Sabon Garin Yan Kwaya",
    "Badakkara",
    "Faruq Labaran Relief",
    "Raudakayi 2",
    "Kabarin Wali Relief",
    "Bagudu Relief",
    "Kawo Burus",
    "B Oloja Old",
    "Bara Musa",
    "Yahaya Mai Welder Old",
    "Nazzalco",
    "Amasco",
    "Yan dodo Relief",
    "Sauna 1",
    "CBN Relief",
    "Sayoka Relief",
    "Yandoji",
    "Kings Garden",
    "Tin Shama Old",
    "Sauna 2",
    "Chairman",
    "Masallacin Izala",
    "Mai Siminti", 
    "Kademi Bakin Kasuwa",
    "Yan Dodo",
    "Walawai Old",
    "Rimi 1",
    "Sauna 3",
    "Laraar Gadon Sarki",
    "Dogon Rimi Relief",
    "Kademi 1",
    "DAURAWA",
    "DAN MARKE",
    "Shehu Na Kwarai",
    "Garin Ali 1",
    "Rangaza Inken Old",
    "Tsamiya Duhuwa Village",
    "Rakad Relief",
    "Yan Audu",
    "Gano Police Station",
    "Gidan Gobirawa Relief",
    "Dakata Village",
    "Ado Gwaram",
    "Mai Cement Relief",
    "FILIN CASHEW",
    "Walawa Raudakayi Nazalco",
    "Roba",
    "Satame",
    "Sullubawa",
    "Bingi",
    "Sabon Gari Daudu",
    "Oposite Viva Junction",
    "Dakata Old",
    "Kademi 2",
    "Dorawar Na Abba Relief",
    "Ajingi 1",
    "Gano Bakin Kasuwa",
    "Gidan Guna",
    "Wuro Bagga Relief",
    "Dorawar Na Abba 1",
    "Salmande",
    "Warshu Hospital Relief",
    "Jiyayyar Wanzamai",
    "Sayoka Old",
    "NNPC",
    "Tudun Karago",
    "Kafin Malamai",
    "Yankatsari Old",
    "Kunya 2",
    "Rimi 2",
    "Kanti Sumaila",
    "Faudan",
    "Gano Kofar Fada",
    "Shagogo",
    "Kwana Shida Relief",
    "Ladanai 1",
    "Menore",
    "Tashar Kuka",
    "Dan Bagina",
    "Ladanai Ungur Kwari",
    "Ali Baba Relief",
    "Faragai",
    "Zuda Relief",
    "Sabon Garin Naira",
    "Unguwar Fulani Farawa",
    "MAKADA",
    "TAMBURAWAR GABAS",
    "Daurawa 1",
    "Garin Dau 1",
    "Makwalla Sumaila",
    "Makole 1 Gwarzo Relief",
    "Sabon Garin Ilu",
    "Yan Gizo",
    "HVDS",
    "Dabuwawa",
    "Jigawar Alhaji Ado",
    "Kargon Kanawa",
    "Daurawa 2",
    "Rimi Kofar Yamma",
    "Talatan Tambutu",
    "Kangayau",
    "Santsin Yan Awaki",
    "Charka",
    "Yan Dalla",
    "Filin Kashu",
    "Kuka Relief",
    "Zango Bus Stop",
    "Yar Gaya Cikin Gari",
    "Kanawa",
    "Dispensary",
    "Garko Makwalla",
    "Dan Borno",
    "Silluru",
    "Zogarawa",
    "Dugwal",
    "Dingamu",
    "Falali 1",
    "Sani Garba",
    "Masallaci Riruwai",
    "Store",
    "Kamfani",
    "Wudil Gaban Komi",
    "FAMFON DAN YOBE(SHARED)"];

         // Initialize feeder_id and batch size
        let feeder_id = 1;
        const batchSize = 5;
        const maxFeederId = 184;

        for (let i = 0; i < dtNames.length; i += batchSize) {
            // Skip feeder IDs 37, 80, 120
            while (feeder_id === 37 || feeder_id === 80 || feeder_id === 120) {
                feeder_id++;
            }

            // Stop if feeder_id exceeds 184
            if (feeder_id > maxFeederId) {
                break;
            }

            const batch = dtNames.slice(i, i + batchSize);

            // Insert batch into the database
            for (const dt of batch) {
                const query = `
                    INSERT INTO DistributionChannel (DT_names, feeder_id)
                    VALUES ('${dt}', ${feeder_id});
                `;
                await sql.query(query);
            }

            // Increment feeder_id after every batch
            feeder_id++;
        }

        console.log('Data inserted successfully.');
        // Count the total number of DTs
        const totalDTs = dtNames.length;

        console.log(`Total number of DTs: ${totalDTs}`);
    } catch (err) {
        console.error('Error inserting data:', err);
    } finally {
        sql.close(); // Close the connection
    }
}

// Run the function
insertDTs();